version: '2.18'
services:
  keycloak:
    container_name: keycloak
    build:
      context: ./
      dockerfile: ./docker/keycloak/Dockerfile
    command: start-dev 
    env_file:
      - ./.env
    ports:
      - "8080:8080"

volumes:
  keycloak_data: